### ISSUE TITLE
Questions about implementation different from the GatedConv paper

### ISSUE THREAD

**Issue by dldms1345** [csqiangwen/DeepFillv2_Pytorch#3]
Hi, thank you for your code.
I have some questions.
1. Is there a reason why sn is set to True in the class TransposeGatedConv2d of network_module.py file? It is used directly on the generator.
2. Do you think excluding perceptual loss in this implementation will not affect the result?

Thank you!

**Comment by csqiangwen** [comment]
Thanks for your question.

1. Only the sn in Discriminator was set to True. I haven't found any sn set True in Generator. The sn is a trick proposed in https://arxiv.org/pdf/1802.05957.pdf to stabilize the discriminator training.
2. Since my limited GPU memory, it will be tough to use gan loss and perceptual loss simultaneously. I think the perceptual loss will have a positive effect on the final result. I am not sure. And I am also curious about this. Thanks for mentioning it.
